[package]
name = "bid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
borsh = "0.9.3"
smart_contract = { package = "pchain-sdk", version = "0.2" }

